name: examples
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  state_watcher:
    path: ../packages/state_watcher
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  meta: ^1.10.0
  go_router: ^13.0.1
  http: ^1.2.0
  pubspec_parse: ^1.2.3
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1  

flutter:
  uses-material-design: true
  assets:
    - assets/pub/
