name: Build

on:
  push:
  pull_request:

jobs:
  sanity_check:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        package:
          - packages/state_watcher
        channel:
          - stable
          - beta
          - master
        include:
          - channel: stable
            test: true

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Removing example folder
        run: rm -rf example
        working-directory: ${{ matrix.package }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - if: ${{ matrix.test }}
        name: Check format
        run: dart format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - if: ${{ matrix.test }}
        name: Run tests
        run: flutter test --coverage
        working-directory: ${{ matrix.package }}

      - if: ${{ matrix.test }}
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}