name: Build

on:
  push:
  pull_request:

jobs:
  sanity_check:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        package:
          - packages/state_watcher
        channel:
          - stable
          - beta
          - master

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Removing example folder
        run: rm -rf example
        working-directory: ${{ matrix.package }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}